version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    labels: ['dependencies']
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'docker'
    directories:
      - '/apps/admin'
      - '/apps/dialog'
    labels: ['dependencies']
    schedule:
      interval: 'weekly'
    ignore:
      # Ignore major version updates for Node.js (required to receive minor updates when staying on LTS)
      - dependency-name: 'node'
        update-types: ['version-update:semver-major']
    groups:
      # Group safe, non-breaking bumps to reduce PRs
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'docker-compose'
    directories:
      - '/apps/dialog/e2e'
      - '/apps/dialog/e2e/mock'
      - '/devops/docker'
    labels: ['dependencies']
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/'
    labels: ['dependencies']
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 5
    groups:
      # Group safe, non-breaking bumps to reduce PRs
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
