version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    labels: ['dependencies']
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'docker'
    directories:
      - '/apps/admin'
      - '/apps/dialog'
    labels: ['dependencies']
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'docker-compose'
    directories:
      - '/apps/dialog/e2e'
      - '/apps/dialog/e2e/mock'
      - '/devops/docker'
    labels: ['dependencies']
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/'
    labels: ['dependencies']
    schedule:
      interval: 'daily'
    groups:
      # Group safe, non-breaking bumps to reduce PRs
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
