name: telli

services:
  postgres:
    # Use the same postgres version as in production
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      POSTGRES_DB: telli_dialog_db
      POSTGRES_USER: telli_dialog_db
      POSTGRES_PASSWORD: test1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U telli_dialog_db -d telli_dialog_db' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  valkey:
    image: ghcr.io/valkey-io/valkey:8
    restart: always
    volumes:
      - valkey_data:/data
    ports:
      - '6379:6379'

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.5
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
      - keycloak_data:/opt/keycloak/data/h2
    ports:
      - '8080:8080'
    restart: always

volumes:
  keycloak_data:
  postgres_data:
  valkey_data: