name: telli

services:
  postgres:
    # Use the same postgres version as in production
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      POSTGRES_DB: telli_dialog_db
      POSTGRES_USER: telli_dialog_db
      POSTGRES_PASSWORD: test1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U telli_dialog_db -d telli_dialog_db']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  valkey:
    image: ghcr.io/valkey-io/valkey:8
    restart: always
    volumes:
      - valkey_data:/data
    ports:
      - '6379:6379'

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.7
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      CLIENT_NAME: telli-dev-client
      CLIENT_SECRET: ClientSecret
    entrypoint: /opt/keycloak/data/import/entrypoint.sh
    volumes:
      - keycloak_data:/opt/keycloak/data/h2
      - ./keycloak:/opt/keycloak/data/import
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      fix-keycloak-volume-ownership:
        condition: service_completed_successfully

  # keycloak runs with uid 1000, but docker creates volumes with root as owner; use a one-shot container to fix the permission
  fix-keycloak-volume-ownership:
    image: alpine
    restart: no
    entrypoint: /bin/sh -c "chown 1000 /keycloak"
    volumes:
      - keycloak_data:/keycloak

  rabbitmq:
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_USER: user
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  keycloak_data:
  postgres_data:
  valkey_data:
